### ISSUE TITLE
Invalid issue tracker URL

### ISSUE THREAD

**Issue by eserte** [barefootcoder/date-easy#1]
search.cpan.org points to https://github.com/me/date-easy/issues for reporting bugs, but that URL only gives a 404 page.

**Comment by barefootcoder** [comment]
Good catch.  I think this is something that Dist::Zilla was supposed to fill in for me, but I probably have a misconfiguration.  (Or maybe I just copy-pasted something I was supposed to modify and didn't notice I needed to modify it.)  I'll get it fixed.

**Comment by barefootcoder** [comment]
Found it: it's a bug in my plugin bundle.  Started issue barefootcoder/dist-zilla-pluginbundle-barefoot#13 to track that.  Once I fix that, the next release of this should come out correct.

**Comment by barefootcoder** [comment]
Fixed in 0.02.
