### ISSUE TITLE
Tests fail on most systems

### ISSUE THREAD

**Issue by eserte** [barefootcoder/date-easy#2]
See http://matrix.cpantesters.org/?dist=Date-Easy+0.01 for an overview of test reports.

**Comment by barefootcoder** [comment]
This one I already knew about, but it's proving difficult to pin down.  I hope to have more time this weekend to devote to just that.  There's definitely a pattern to which smokers fail it and which pass it, but it's not anything so simple as OS or Perl version (or even threaded, though I think that's closer).  Once I finish tweaking my `cpan-testers` script (shamelessly stolen from [tobyink's original](http://www.perlmonks.org/?node_id=978606)), I should be able to figure it out precisely, which will hopefully enable me to reproduce it locally, and then it should be fairly easy to fix.

**Comment by barefootcoder** [comment]
The primary cause of the failures was fixed, as described on [my blog](http://blogs.perl.org/users/buddy_burden/2016/04/a-date-with-cpan-part-8-curse-you-daylight-savings-time.html).  There are still some lingering failures, but they're down to less than half the total reports, and thanks to @eserte there are separate issues for those now.  So I'm closing this one out.
